---
swagger: "2.0"
info:
  description: "Necessary API to support requests from IGE remastered"
  version: "1.0.0"
  title: "IGE remastered API"
host: "localhost"
basePath: "/v1"
schemes:
- "http"
- "https"
produces:
- "application/json"
paths:
  /user/list:
    get:
      operationId: list
      summary: ""
      description: ""
      responses:
        '200':
          description: Returns the list of users
      tags:
      - "User"
    x-swagger-router-controller: "User"
  /user/{id}:
    options:
      summary: ""
      description: ""
      operationId: optionsUser
      parameters:
      - name: "id"
        in: "path"
        description: "The unique login of the user."
        required: true
        type: "string"
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        '200':
          description: Options for this operation are returned.
      tags:
      - "User"
    get:
      operationId: getUser
      summary: ""
      description: ""
      parameters:
      - name: "id"
        in: "path"
        description: "The unique login of the user."
        required: true
        type: "string"
      responses:
        '200':
          description: Returns the user
      tags:
      - "User"
    post:
      operationId: setUser
      summary: "Updates a user. If user could not be found an error will be returned."
      description: ""
      parameters:
      - name: "id"
        in: "path"
        description: "The unique login of the user."
        required: true
        type: "string"
      - name: "user"
        in: "body"
        description: "Save the user data into the database."
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        '200':
          description: User was successfully updated
        '406':
          description: A user with the given login does not exist and cannot be updated
      tags:
      - "User"
    put:
      operationId: createUser
      summary: "Creates a new user. If user with a given login already exists an error will be returned."
      description: ""
      parameters:
      - name: "id"
        in: "path"
        description: "The unique login of the user."
        required: true
        type: "string"
      - name: "user"
        in: "body"
        description: "Save the user data into the database."
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        '200':
          description: User was successfully created
        '406':
          description: A user already exists with the given login
      tags:
      - "User"
    delete:
      operationId: deleteUser
      summary: "Deletes a user."
      description: "If user with a given login does not exists an error will be returned."
      parameters:
      - name: "id"
        in: "path"
        description: "The unique login of the user."
        required: true
        type: "string"
      responses:
        '200':
          description: User was successfully deleted
        '406':
          description: A user with the given login does not exist and cannot be deleted
      tags:
      - "User"
    x-swagger-router-controller: "User"
  /user/login:
    post:
      operationId: login
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: username
        in: formData
        type: string
        required: false
      - name: password
        in: formData
        type: string
        required: false
      responses:
        '200':
          description: Return the JWT
        '403':
          description: Error when user is not accepted.
      tags:
      - "User"
    x-swagger-router-controller: "User"
  /behaviours:
    options:
      summary: ""
      description: ""
      operationId: optionsBehaviours
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        '200':
          description: Options for this operation are returned.
      tags:
      - "Behaviour"
    get:
      summary: ""
      description: ""
      operationId: get
      responses:
        '200':
          description: Behaviours are returned.
      tags:
      - "Behaviour"
    post:
      summary: ""
      description: ""
      operationId: setBehaviours
      parameters:
        - name: "behaviour"
          in: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/Behaviour"
      responses:
        '200':
          description: Behaviours have been set.
      tags:
      - "Behaviour"
    x-swagger-router-controller: "Behaviours"
  /datasets/find:
    options:
      tags:
        - "Datasets"
      summary: ""
      description: ""
      operationId: optionsDatasets
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        '200':
          description: Options for this operation are returned.
    get:
      tags:
      - "Datasets"
      summary: ...
      description: ""
      operationId: find
      parameters:
      - name: "query"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "fields"
        in: "query"
        description: ""
        required: true
        type: "string"
      responses:
        '200':
          description: Datasets found
    x-swagger-router-controller: "Datasets"
  /datasets/children:
    options:
      tags:
      - "Datasets"
      summary: ""
      description: ""
      operationId: "optionsChildren"
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        '200':
          description: Options for this operation are returned.
      x-swagger-router-controller: "Datasets"
    get:
      tags:
      - "Datasets"
      summary: ...
      description: ""
      operationId: children
      security: [{"jwt": []}]
      parameters:
      - name: "parentId"
        in: "query"
        description: "The ID of the parent dataset to get the children from. If empty then the root datasets are returned."
        required: false
        type: "string"
      - name: "fields"
        in: "query"
        description: ""
        required: true
        type: "string"
      responses:
        '200':
          description: Datasets found
      x-swagger-router-controller: "Datasets"
  /dataset/path/{id}:
    get:
      tags:
      - "Datasets"
      summary: "Get the hierarchical path of a document"
      description: "Retrieve an array of ID of all parents leading to the given dataset ID."
      operationId: "getPath"
      parameters:
      - name: "id"
        in: "path"
        description: "The ID of the dataset."
        required: true
        type: "string"
      responses:
        '200':
          description: Array of IDs.
      x-swagger-router-controller: "Datasets"
  /dataset/{id}:
    options:
      tags:
      - "Datasets"
      summary: ...
      description: ""
      operationId: getByIDOperation
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      - application/xml
      parameters:
      - name: "id"
        in: "path"
        description: "The ID of the dataset."
        required: true
        type: "string"
      - name: "publish"
        in: "query"
        description: "If we want to get the published version then this parameter\
          \ has to be set to true."
        required: false
        type: "boolean"
      - name: "revert"
        in: "query"
        description: "Delete the draft version and make the published version the current one."
        required: false
        type: "boolean"
      responses:
        '200':
          description: Dataset updated.
        '405':
          description: Invalid input
      x-swagger-router-controller: "Datasets"
    get:
      tags:
      - "Datasets"
      summary: "A complete dataset"
      description: "Retrieve a dataset by a given ID."
      operationId: "getByID"
      parameters:
      - name: "id"
        in: "path"
        description: "The ID of the dataset."
        required: true
        type: "string"
      - name: "publish"
        in: "query"
        description: "If we want to get the published version then this parameter\
          \ has to be set to true."
        required: false
        type: "boolean"
      responses:
        200:
          description: "The dataset with the given ID."
          schema:
            $ref: "#/definitions/Dataset"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Datasets"
    post:
      tags:
      - "Datasets"
      summary: "Set a complete dataset"
      description: "xxx"
      operationId: "setDatasets"
      parameters:
      - name: "id"
        in: "path"
        description: "The ID of the dataset."
        required: true
        type: "string"
      - name: "data"
        in: "body"
        description: "The dataset to be stored."
        required: true
        schema:
          $ref: "#/definitions/DatasetClient"
      - name: "publish"
        in: "query"
        description: "If we want to store the published version then this parameter\
          \ has to be set to true."
        required: false
        type: "boolean"
      - name: "revert"
        in: "query"
        description: "Delete the draft version and make the published version the current one."
        required: false
        type: "boolean"
      responses:
        200:
          description: "The stored dataset, which might contain additional storage\
            \ information."
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Datasets"
    delete:
      tags:
      - "Datasets"
      summary: "Deletes a dataset"
      description: "..."
      operationId: "deleteById"
      parameters:
      - name: "id"
        in: "path"
        description: "The ID of the dataset."
        required: true
        type: "string"
      responses:
        200:
          description: ""
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Datasets"
securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    type: "object"
    required:
    - login
    properties:
      login:
        type: "string"
        description: ""
      firstName:
        type: "string"
        description: ""
      lastName:
        type: "string"
        description: ""
  Dataset:
    type: "object"
    required:
    - _created
    properties:
      _id:
        type: "string"
        description: "Unique identifier"
      _profile:
        type: "string"
        description: "Description of the dataset."
      _created:
        type: "string"
        description: "The date the dataset was created."
      _modified:
        type: "string"
        description: "The date the dataset was last modified."
      _published:
        type: "string"
        description: "The date the dataset was last published."
  DatasetClient:
    type: "object"
    properties:
      _id:
        type: "string"
        description: "Unique identifier"
      _profile:
        type: "string"
        description: "Description of the dataset."
  Behaviour:
    type: "object"
    properties:
      _id:
        type: "string"
        description: "Unique identifier"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
