---
swagger: "2.0"
info:
  description: "Necessary API to support requests from IGE remastered"
  version: "1.0.0"
  title: "IGE remastered API"
host: "localhost"
basePath: "/v1"
schemes:
- "http"
- "https"
produces:
- "application/json"
paths:
  /behaviours:
    options:
      summary: ""
      description: ""
      operationId: options
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      responses:
        '200':
          description: Options for this operation are returned.
    get:
      summary: ""
      description: ""
      operationId: get
      responses:
        '200':
          description: Behaviours are returned.
    post:
      summary: ""
      description: ""
      operationId: set
      parameters:
        - name: "behaviour"
          in: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/Behaviour"
      responses:
        '200':
          description: Behaviours have been set.
    x-swagger-router-controller: "Behaviours"
  /datasets/find:
    get:
      tags:
      - "Datasets"
      summary: ...
      description: ""
      operationId: find
      parameters:
      - name: "query"
        in: "query"
        description: ""
        required: true
        type: "string"
      - name: "fields"
        in: "query"
        description: ""
        required: true
        type: "string"
      responses:
        '200':
          description: Datasets found
      x-swagger-router-controller: "Datasets"
  /datasets/children:
    get:
      tags:
      - "Datasets"
      summary: ...
      description: ""
      operationId: children
      parameters:
      - name: "parentId"
        in: "query"
        description: "The ID of the parent dataset to get the children from. If empty then the root datasets are returned."
        required: false
        type: "string"
      - name: "fields"
        in: "query"
        description: ""
        required: true
        type: "string"
      responses:
        '200':
          description: Datasets found
      x-swagger-router-controller: "Datasets"
  /dataset/{id}:
    options:
      tags:
      - "Datasets"
      summary: ...
      description: ""
      operationId: getByIDOperation
      consumes:
      - application/x-www-form-urlencoded
      produces:
      - application/json
      - application/xml
      parameters:
      - name: "id"
        in: "path"
        description: "The ID of the dataset."
        required: true
        type: "string"
      - name: "publish"
        in: "query"
        description: "If we want to get the published version then this parameter\
          \ has to be set to true."
        required: false
        type: "boolean"
      - name: "revert"
        in: "query"
        description: "Delete the draft version and make the published version the current one."
        required: false
        type: "boolean"
      responses:
        '200':
          description: Dataset updated.
        '405':
          description: Invalid input
      x-swagger-router-controller: "Datasets"
    get:
      tags:
      - "Datasets"
      summary: "A complete dataset"
      description: "Retrieve a dataset by a given ID."
      operationId: "getByID"
      parameters:
      - name: "id"
        in: "path"
        description: "The ID of the dataset."
        required: true
        type: "string"
      - name: "publish"
        in: "query"
        description: "If we want to get the published version then this parameter\
          \ has to be set to true."
        required: false
        type: "boolean"
      responses:
        200:
          description: "The dataset with the given ID."
          schema:
            $ref: "#/definitions/Dataset"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Datasets"
    post:
      tags:
      - "Datasets"
      summary: "Set a complete dataset"
      description: "xxx"
      operationId: "set"
      parameters:
      - name: "id"
        in: "path"
        description: "The ID of the dataset."
        required: true
        type: "string"
      - name: "data"
        in: "body"
        description: "The dataset to be stored."
        required: true
        schema:
          $ref: "#/definitions/DatasetClient"
      - name: "publish"
        in: "query"
        description: "If we want to store the published version then this parameter\
          \ has to be set to true."
        required: false
        type: "boolean"
      - name: "revert"
        in: "query"
        description: "Delete the draft version and make the published version the current one."
        required: false
        type: "boolean"
      responses:
        200:
          description: "The stored dataset, which might contain additional storage\
            \ information."
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Datasets"
    delete:
      tags:
      - "Datasets"
      summary: "Deletes a dataset"
      description: "..."
      operationId: "deleteById"
      parameters:
      - name: "id"
        in: "path"
        description: "The ID of the dataset."
        required: true
        type: "string"
      responses:
        200:
          description: ""
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Datasets"
definitions:
  Dataset:
    type: "object"
    required:
    - _created
    properties:
      _id:
        type: "string"
        description: "Unique identifier"
      _profile:
        type: "string"
        description: "Description of the dataset."
      _created:
        type: "string"
        description: "The date the dataset was created."
      _modified:
        type: "string"
        description: "The date the dataset was last modified."
      _published:
        type: "string"
        description: "The date the dataset was last published."
  DatasetClient:
    type: "object"
    properties:
      _id:
        type: "string"
        description: "Unique identifier"
      _profile:
        type: "string"
        description: "Description of the dataset."
  Behaviour:
    type: "object"
    properties:
      _id:
        type: "string"
        description: "Unique identifier"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
