package de.ingrid.igeserver.profiles.ingrid_lubw_skdv_ok

val codelist30000 = mapOf(
    "99" to "Landesamt für Denkmalpflege",
    "31" to "Ministerium für Umwelt, Klima und Energiewirtschaft",
    "64" to "Landesanstalt für Umwelt Baden-Württemberg",
    "65" to "Regierungspräsidien (Umweltschutzverwaltung)",
    "66" to "Regierungspräsidien (Naturschutzverwaltung)",
    "67" to "Regierungspräsidien (Landwirtschaftsverwaltung)",
    "68" to "Regierungspräsidien (Forstverwaltung)",
    "70" to "Regierungspräsidien (Straßenbauverwaltung)",
    "71" to "Regierungspräsidium Freiburg (Landesamt für Geologie, Rohstoffe und Bergbau)",
    "72" to "Regierungspräsidien (Raumordnung)",
    "73" to "Landratsämter/Bürgermeisterämter (Umweltschutzverwaltung)",
    "74" to "Landratsämter/Bürgermeisterämter (Naturschutzverwaltung)",
    "75" to "Landratsämter/Bürgermeisterämter (Landwirtschaftsverwaltung)",
    "76" to "Landratsämter/Bürgermeisterämter (Forstverwaltung)",
    "77" to "Landratsämter/Bürgermeisterämter (Flurneuordnung)",
    "78" to "Landratsämter/Bürgermeisterämter (Straßenbauverwaltung)",
    "79" to "Landratsämter/Bürgermeisterämter (Vermessungsdienststellen)",
    "80" to "Ministerium für Landesentwicklung und Wohnen",
    "81" to "Ministerium für Ernährung, Ländlichen Raum und Verbraucherschutz",
    "82" to "Sonderabfallagentur Baden-Württemberg GmbH",
    "84" to "Statistisches Landesamt",
    "85" to "Regionalverbände",
    "86" to "Gemeinden",
    "87" to "Gemeinden (Umweltschutzverwaltung)",
    "88" to "Nationalpark Schwarzwald",
    "89" to "Forstliche Versuchs- und Forschungsanstalt",
    "90" to "Sozialministerium",
    "91" to "Baurechtsbehörden",
    "92" to "Landesanstalt für Entwicklung der Landwirtschaft",
    "93" to "Sonstige",
    "94" to "Chemisches und Veterinäruntersuchungsamt",
    "96" to "Informatikzentrum Landesverwaltung Baden-Württemberg",
    "97" to "Landratsämter/Bürgermeisterämter (sonstige Verwaltung)",
    "98" to "Landesamt für Geoinformation und Landentwicklung Baden-Württemberg",
    "83" to "Ministerium für Verkehr",
    "30" to "Mobilitätszentrale",
    "69" to "Fischereiforschungsstelle",
)

val codelist30001 = mapOf(
    "1" to "Umweltinformationssystem Baden-Württemberg (UIS)",
    "5" to "Informationssystem Wasser, Immissionsschutz, Boden, Abfall, Arbeitsschutz (WIBAS)",
    "2" to "Naturschutzinformationssystem (NAIS)",
    "48" to "Allgemeine Denkmaldatenbank (ADABweb)",
    "6" to "Adressdienst (ADR)",
    "7" to "Anlagenbezogener Gewässerschutz, Abfallanlagen (AGS)",
    "35" to "Automatisiertes Raumordnungskataster (AROK)",
    "50" to "Amtliches Digitales Wasserwirtschaftliches Gewässernetz (AWGN)",
    "18" to "Verwaltung von Anlagen zum Umgang mit wassergefährdenden Stoffen (AwSV)",
    "12" to "Fachanwendung Bodenschutz- und Altlastenkataster (BAK)",
    "10" to "Berichtssystem (BRS)",
    "11" to "Berechtigungsdienst (BV-Admin)",
    "51" to "Energieatlas Baden-Württemberg (EEBW)",
    "41" to "Fachanwendung Arbeitsschutz / Immissionsschutz Gewerbeaufsicht (FA AI-GWA)",
    "24" to "Fachanwendung Störfall-Verordnung (FA StörfallV)",
    "43" to "Fachanwendung Tätigkeitsstatistik Gewerbeaufsicht (FA TS-GWA)",
    "9" to "Fachanwendung Wasserrecht",
    "47" to "Fachanwendung 26. BImSchV Gewerbeaufsicht (FA 26. BImSchV)",
    "20" to "Fachanwendungen Arbeits- und Immissionsschutz, Industrieabwasser, Abfallanlagen, Strahlenschutz/Röntgen (FA-GWA)",
    "13" to "Fachinformationssystem Bodenschutz (FIS-BO)",
    "45" to "Integrierte Geowissenschaftliche Landesaufnahme (GeoLa)",
    "14" to "Gewässer-Informationssystem (GewIS)",
    "15" to "Grundwasserdatenbank (GWDB)",
    "55" to "Hochwasserrisikomanagement",
    "53" to "Kommunale Fachanwendungen",
    "16" to "Labordatenübertragungssystem (LABDÜS)",
    "26" to "Landentwicklungs-GIS (LEGIS)",
    "17" to "Managementsystem Abwasserabgaben (MAWAG)",
    "52" to "Nutzerorientiert aufbereitete Geobasisdaten Baden-Württemberg (NORA_BW)",
    "37" to "PlanAtlas Baden-Württemberg (PlanAtlas)",
    "22" to "Straßeninformationsbank Baden-Württemberg (SIB)",
    "54" to "Starkregenrisikomanagement",
    "29" to "Wasser- und Bodenatlas Baden-Württemberg (WaBoA)",
    "49" to "Wasserwirtschaftliche Gebiete (WawiG)",
    "19" to "Wasserentnahmeentgelt (WEE)",
    "28" to "Keine Angabe zur Hauptanwendung",
    "99" to "sonstige Anwendung",
)

val codelist30004 = mapOf(
    "1" to "1 - unbeschränkt (im Internet)",
    "2" to "2 - beschränkt auf die öffentliche Verwaltung (LVN und KVN)",
    "3" to "3 - beschränkt auf alle Partner des SKDV-Datenverbund pauschal ohne Vorprüfung",
    "4" to "4 - beschränkt auf bestimmte Behörden, Mitgliedsgemeinden des SKDV-Datenverbunds (bezeichnet nach Auswahlliste)",
    "5" to "5 - beschränkt auf Umwelt- und Naturschutzbehörden",
    "6" to "6 - beschränktes Leserecht im Einzelfall",
)
