version: '3'
services:

  keycloak:
    image: docker-registry.wemove.com/keycloak:22.0.4-2
    restart: unless-stopped
    environment:
      - SIMPLE_SECURITY=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_RELATIVE_PATH=
      - KC_HOSTNAME=
      - KC_HOSTNAME_URL=http://localhost:8080
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_DB=postgres
      - KC_DB_URL_HOST=db
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
      - MAIL_SMTP=mailrelay
      - MAIL_FROM=keycloak@wemove.com
      #- IGE_CLIENT_ID=ige-ng
      - IGE_FRONTEND_URL=http://localhost:4300
      - IGE_SUPER_USER_LOGIN=ige
      - IGE_SUPER_USER_PASSWORD=ige
      - IGE_SUPER_USER_FIRSTNAME=Super
      - IGE_SUPER_USER_LASTNAME=User
      - IGE_SUPER_USER_EMAIL=super@user.test
    ports:
      - "8080:8080"
    networks:
      - ige-ng-network

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    environment:
      - cluster.name=ingrid
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - http.cors.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      #- xpack.security.enabled=true
      #- ELASTIC_PASSWORD=admin
      #- xpack.security.http.ssl.enabled=true
      #- xpack.security.http.ssl.keystore.path=http.p12
      # - ELASTICSEARCH_KEYSTORE_PASSWORD=
    restart: unless-stopped
    # volumes:
      # - ./set-keystore-password.sh:/usr/share/elasticsearch/bin/set-keystore-password.sh
      # - ./elasticsearch-ssl-http/elasticsearch/http.p12:/usr/share/elasticsearch/config/http.p12
    # entrypoint: [ "/bin/bash", "-c", "/usr/share/elasticsearch/bin/set-keystore-password.sh && /usr/local/bin/docker-entrypoint.sh eswrapper" ]
    ports:
      - "9200:9200"
    networks:
      - ige-ng-network

  db:
    image: "postgres"
    restart: unless-stopped
    tmpfs:
      - /run
      - /var/cache
      - /pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /pgdata
    networks:
      - ige-ng-network

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - ige-ng-network

  umami:
    image: docker.umami.is/umami-software/umami:postgresql-latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://admin:admin@db:5432/umami
    ports:
      - "3000:3000"
    networks:
      - ige-ng-network

networks:
  ige-ng-network:
    driver: "bridge"
