version: '3'
services:

  keycloak:
    image: docker-registry.wemove.com/keycloak:19.0.3-1-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - ige-ng-network

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    environment:
      - cluster.name=ingrid
      - discovery.type=single-node
      - ingest.geoip.downloader.enabled=false
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - ige-ng-network

  db:
    image: "postgres"
    restart: unless-stopped
    tmpfs:
      - /run
      - /var/cache
      - /pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /pgdata

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

networks:
  ige-ng-network:
    driver: "bridge"
