/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import de.ingrid.igeserver.model.Data5;
import de.ingrid.igeserver.model.InlineResponseDefault;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-08-21T10:21:42.666Z")

@Api(value = "export", description = "the export API")
public interface ExportApi {

    @ApiOperation(value = "...", notes = "...", response = Void.class, tags = { "Export", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "The stored dataset, which might contain additional storage information.", response = Void.class),
            @ApiResponse(code = 200, message = "Unexpected error", response = InlineResponseDefault.class) })

    @RequestMapping(value = "/export", produces = { "application/json" }, method = RequestMethod.POST)
    ResponseEntity<Void> exportDataset2(@ApiParam(value = "The dataset to be exported.", required = true) @Valid @RequestBody Data5 data);

}
