/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestPart;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-08-21T10:21:42.666Z")

@Api(value = "login", description = "the login API")
@RequestMapping(path="/api")
public interface LoginApi {

    @ApiOperation(value = "", notes = "", response = Void.class, tags = { "Security", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Return the JWT", response = Void.class),
            @ApiResponse(code = 403, message = "Error when user is not accepted.", response = Void.class) })
    @RequestMapping(value = "/login", produces = { "application/json" }, consumes = { "application/x-www-form-urlencoded" }, method = RequestMethod.POST)
    ResponseEntity<Void> login(@ApiParam(value = "") @RequestPart(value = "username", required = false) String username,
            @ApiParam(value = "") @RequestPart(value = "password", required = false) String password);
    
//    @ApiOperation(value = "", notes = "", response = Void.class, tags = { "Security", })
//    @ApiResponses(value = {
//            @ApiResponse(code = 200, message = "Return the JWT", response = Void.class),
//            @ApiResponse(code = 403, message = "Error when user is not accepted.", response = Void.class) })
//    @RequestMapping(value = "/logout", produces = { "application/json" }, method = RequestMethod.POST)
//    ResponseEntity<Void> logout();

}
