/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-08-21T10:21:42.666Z")

@Api(value = "refreshToken", description = "the refreshToken API")
@RequestMapping(path="/api")
public interface RefreshTokenApi {

    @ApiOperation(value = "", notes = "", response = Void.class, tags = { "Security" })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Options for this operation are returned.", response = Void.class) })

    @RequestMapping(value = "/refreshToken", produces = { "application/json" }, method = RequestMethod.OPTIONS)
    ResponseEntity<Void> getRefreshOp();

    @ApiOperation(value = "", notes = "", response = Void.class, tags = { "Security", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Returns a new access token to the requested client", response = Void.class) })

    @RequestMapping(value = "/refreshToken", produces = { "application/json" }, method = RequestMethod.GET)
    ResponseEntity<Void> refreshToken();

}
