/**
 * ==================================================
 * Copyright (C) 2024 wemove digital solutions GmbH
 * ==================================================
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */
package de.ingrid.igeserver.profiles.opendata

val codelist505 = mapOf(
    "2" to "Verwalter",
    "6" to "Urheber",
    "7" to "Ansprechpartner",
    "11" to "Autor",
    "12" to "Veröffentlichende Stelle",
)

val codelist20001 = mapOf(
    "SOCI" to "Bevölkerung und Gesellschaft",
    "EDUC" to "Bildung, Kultur und Sport",
    "ENER" to "Energie",
    "HEAL" to "Gesundheit",
    "INTR" to "Internationale Themen",
    "JUST" to "Justiz, Rechtssystem und öffentliche Sicherheit",
    "AGRI" to "Landwirtschaft, Fischerei, Forstwirtschaft und Nahrungsmittel",
    "GOVE" to "Regierung und öffentlicher Sektor",
    "REGI" to "Regionen und Städte",
    "ENVI" to "Umwelt",
    "TRAN" to "Verkehr",
    "ECON" to "Wirtschaft und Finanzen",
    "TECH" to "Wissenschaft und Technologie",
)
val codelist20003 = listOf(
    "ZIP",
    "XML",
    "RDF",
    "SKOS_XML",
    "XLSX",
    "PDF",
    "ARC",
    "ARC_GZ",
    "ATOM",
    "AZW",
    "BIN",
    "BMP",
    "BWF",
    "CSS",
    "CSV",
    "DBF",
    "DCR",
    "DMP",
    "DOC",
    "DOCX",
    "DTD_SGML",
    "DTD_XML",
    "E00",
    "ECW",
    "EPS",
    "EPUB",
    "FMX2",
    "FMX3",
    "FMX4",
    "GDB",
    "GEOJSON",
    "GIF",
    "GML",
    "GMZ",
    "GRID_ASCII",
    "GZIP",
    "HDF",
    "HTML",
    "HTML_SIMPL",
    "INDD",
    "JPEG",
    "JPEG2000",
    "JSON",
    "JSON_LD",
    "KML",
    "KMZ",
    "LAS",
    "LAZ",
    "MAP_PRVW",
    "MAP_SRVC",
    "MBOX",
    "MDB",
    "METS",
    "METS_ZIP",
    "MHTML",
    "MOBI",
    "MOP",
    "MPEG2",
    "MPEG4",
    "MPEG4_AVC",
    "MSG_HTTP",
    "MXD",
    "NETCDF",
    "OCTET",
    "ODB",
    "ODC",
    "ODF",
    "ODG",
    "ODS",
    "ODT",
    "OP_DATPRO",
    "OVF",
    "OWL",
    "PDF1X",
    "PDFA1A",
    "PDFA1B",
    "PDFA2A",
    "PDFA2B",
    "PDFA3",
    "PDFX",
    "PDFX1A",
    "PDFX2A",
    "PDFX4",
    "PNG",
    "PPS",
    "PPSX",
    "PPT",
    "PPTX",
    "PS",
    "PSD",
    "RDFA",
    "RDF_N_QUADS",
    "RDF_N_TRIPLES",
    "RDF_TRIG",
    "RDF_TURTLE",
    "RDF_XML",
    "REST",
    "RSS",
    "RTF",
    "SCHEMA_XML",
    "SDMX",
    "SGML",
    "SHP",
    "SPARQLQ",
    "SPARQLQRES",
    "SQL",
    "TAB",
    "TAB_RSTR",
    "TAR",
    "TAR_GZ",
    "TAR_XZ",
    "TIFF",
    "TIFF_FX",
    "TMX",
    "TSV",
    "TXT",
    "WARC",
    "WARC_GZ",
    "WORLD",
    "XHTML",
    "XHTML_SIMPL",
    "XLIFF",
    "XLS",
    "XSLFO",
    "XSLT",
    "XYZ",
    "BITS",
    "JATS",
    "PWP",
    "JS",
    "N3",
    "RAR",
    "WMS_SRVC",
    "EXE",
    "ICS",
    "MRSID",
    "PL",
    "QGS",
    "SVG",
    "WFS_SRVC",
    "ISO",
    "ISO_ZIP",
    "GRID",
    "XLSB",
    "XLSM",
    "IMMC_XML",
    "HDT",
    "LEG",
    "7Z",
    "AAC",
    "APPX",
    "ARJ",
    "DMG",
    "JAR",
    "MSI",
    "SWM",
    "APK",
    "BZIP2",
    "DEB",
    "LHA",
    "LZMA",
    "ODP",
    "RDF_TRIX",
    "RPM",
    "SB3",
    "WAR",
    "WIM",
    "XZ",
    "Z",
    "EAR",
    "LZIP",
    "LZO",
    "AKN4EU",
    "FMX4_ZIP",
    "ETSI_XML",
    "GPKG",
    "AKN4EU_ZIP",
    "DGN",
    "DWG",
    "DXF",
    "WCS_SRVC",
    "IPA",
    "PDFUA",
    "HTML5",
)

val codelist20004 = mapOf(
    "http://dcat-ap.de/def/licenses/dl-zero-de/2.0" to "Datenlizenz Deutschland – Zero – Version 2.0",
    "http://dcat-ap.de/def/licenses/dl-by-de/2.0" to "Datenlizenz Deutschland Namensnennung 2.0",
    "http://dcat-ap.de/def/licenses/cc-by/4.0" to "Creative Commons Namensnennung – 4.0 International (CC BY 4.0)",
    "http://dcat-ap.de/def/licenses/apache" to "Freie Softwarelizenz der Apache Software Foundation",
    "http://dcat-ap.de/def/licenses/bsd" to "BSD Lizenz",
    "http://dcat-ap.de/def/licenses/cc-by" to "Creative Commons Namensnennung (CC-BY)",
    "http://dcat-ap.de/def/licenses/cc-by-de/3.0" to "Creative Commons Namensnennung 3.0 Deutschland (CC BY 3.0 DE)",
    "http://dcat-ap.de/def/licenses/cc-by-sa" to "Creative Commons Namensnennung - Weitergabe unter gleichen Bedingungen (CC-BY-SA)",
    "http://dcat-ap.de/def/licenses/cc-by-sa-de/3.0" to "Creative Commons Namensnennung - Weitergabe unter gleichen Bedingungen 3.0 Deutschland (CC BY-SA 3.0 DE)",
    "http://dcat-ap.de/def/licenses/cc-by-sa/4.0" to "Creative Commons Namensnennung - Weitergabe unter gleichen Bedingungen 4.0 International (CC-BY-SA 4.0)",
    "http://dcat-ap.de/def/licenses/ccpdm/1.0" to "Public Domain Mark 1.0 (PDM)",
    "http://dcat-ap.de/def/licenses/cc-zero" to "Creative Commons CC Zero License (cc-zero)",
    "http://dcat-ap.de/def/licenses/dl-by-de/1.0" to "Datenlizenz Deutschland Namensnennung 1.0",
    "http://dcat-ap.de/def/licenses/geonutz/20130319" to "Nutzungsbestimmungen für die Bereitstellung von Geodaten des Bundes",
    "http://dcat-ap.de/def/licenses/geoNutz/20131001" to "Nutzungsbestimmungen für die Bereitstellung von Geodaten des Landes Berlin",
    "http://dcat-ap.de/def/licenses/gfdl" to "GNU Free Documentation License (GFDL)",
    "http://dcat-ap.de/def/licenses/gpl/3.0" to "GNU General Public License version 3.0 (GPLv3)",
    "http://dcat-ap.de/def/licenses/mozilla" to "Mozilla Public License 2.0 (MPL)",
    "http://dcat-ap.de/def/licenses/odbl" to "Open Data Commons Open Database License (ODbL)",
    "http://dcat-ap.de/def/licenses/odby" to "Open Data Commons Attribution License (ODC-BY 1.0)",
    "http://dcat-ap.de/def/licenses/odcpddl" to "Open Data Commons Public Domain Dedication and Licence (ODC PDDL)",
    "http://dcat-ap.de/def/licenses/officialWork" to "Amtliches Werk, lizenzfrei nach §5 Abs. 1 UrhG",
    "http://dcat-ap.de/def/licenses/other-open" to "Andere offene Lizenz",
    "http://dcat-ap.de/def/licenses/other-opensource" to "Andere Open Source Lizenz",
    "http://dcat-ap.de/def/licenses/cc-by-nc" to "Creative Commons Namensnennung - Nicht kommerziell (CC BY-NC)",
    "http://dcat-ap.de/def/licenses/cc-by-nc-de/3.0" to "Creative Commons Namensnennung - Nicht kommerziell 3.0 Deutschland (CC BY-NC 3.0 DE)",
    "http://dcat-ap.de/def/licenses/cc-by-nc/4.0" to "Creative Commons Namensnennung - Nicht kommerziell 4.0 International (CC BY-NC 4.0)",
    "http://dcat-ap.de/def/licenses/cc-by-nd" to "Creative Commons Namensnennung - Keine Bearbeitung (CC BY-ND)",
    "http://dcat-ap.de/def/licenses/cc-by-nd/3.0" to "Creative Commons Namensnennung - Keine Bearbeitung 3.0 Unported (CC BY-ND 3.0)",
    "http://dcat-ap.de/def/licenses/cc-by-nd/4.0" to "Creative Commons Namensnennung - Keine Bearbeitung 4.0 International (CC BY-ND 4.0)",
    "http://dcat-ap.de/def/licenses/dl-by-nc-de/1.0" to "Datenlizenz Deutschland Namensnennung nicht-kommerziell 1.0",
    "http://dcat-ap.de/def/licenses/other-closed" to "Andere geschlossene Lizenz",
    "http://dcat-ap.de/def/licenses/other-commercial" to "Andere kommerzielle Lizenz",
    "http://dcat-ap.de/def/licenses/other-freeware" to "Andere Freeware Lizenz"
)

val codelist20005 = mapOf(
    "TEMPORARY" to "Daten können jederzeit verschwinden. (TEMPORARY)",
    "EXPERIMENTAL" to "Daten versuchsweise verfügbar, sind aber noch etwa ein Jahr erreichbar. (EXPERIMENTAL)",
    "AVAILABLE" to "Daten sind für einige Jahre verfügbar, mittelfristige Planung. (AVAILABLE)",
    "STABLE" to "Daten werden langfristig erhältlich bleiben. (STABLE)",
    "OP_DATPRO" to "Vorläufige Daten. (OP_DATPRO)"
)

val codelist20006 = mapOf(
    "international" to "internationale Ebene",
    "european" to "EU-Ebene",
    "federal" to "Bundesebene",
    "state" to "Ebene der Bundesländer",
    "administrativeDistrict" to "Ebene der Landkreise und Regierungsbezirke",
    "municipality" to "kommunale Ebene",
)

val codelist20007 = mapOf(
    "DEU" to "Deutsch",
    "ENG" to "Englisch",
)