/*
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api

import de.ingrid.igeserver.persistence.postgresql.jpa.model.ige.Behaviour
import io.swagger.v3.oas.annotations.Hidden
import io.swagger.v3.oas.annotations.Parameter
import io.swagger.v3.oas.annotations.responses.ApiResponse
import io.swagger.v3.oas.annotations.responses.ApiResponses
import io.swagger.v3.oas.annotations.tags.Tag
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*
import java.security.Principal

@Hidden
@Tag(name = "Behaviours", description = "the behaviours API")
interface BehavioursApi {
    @ApiResponses(value = [ApiResponse(responseCode = "200", description = "Behaviours are returned.")])
    @GetMapping(value = ["/behaviours"], produces = [MediaType.APPLICATION_JSON_VALUE])
    fun getBehaviours(principal: Principal): ResponseEntity<List<Behaviour>>

    @ApiResponses(value = [ApiResponse(responseCode = "200", description = "Behaviours have been set.")])
    @PostMapping(value = ["/behaviours"], produces = [MediaType.APPLICATION_JSON_VALUE])
    fun setBehaviours(principal: Principal,
                      @Parameter(required = true) @RequestBody behaviours: List<Behaviour>): ResponseEntity<Void>
}
