/*
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api;

import de.ingrid.igeserver.model.InlineResponseDefault;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-08-21T10:21:42.666Z")

@Api(value = "catalogs", description = "the catalog API")
@RequestMapping(path = "/api")
public interface CatalogApi {

    @ApiOperation(value = "", notes = "", response = Void.class, tags = {"Catalog"})
    @ApiResponses(value = {@ApiResponse(code = 200, message = "", response = Void.class),
            @ApiResponse(code = 200, message = "Unexpected error", response = InlineResponseDefault.class)})

    @RequestMapping(value = "/catalogs", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<String[]> getCatalogs();

    // @PreAuthorize("hasRole('admin')")
    @ApiOperation(value = "", notes = "", response = Void.class, tags = {"Catalog"})
    @RequestMapping(value = "/catalogs/{name}", produces = {"application/json"}, method = RequestMethod.POST)
    public ResponseEntity<String> createCatalog(
            @ApiParam(value = "The name of the catalog to create.", required = true) @PathVariable("name") String name) throws ApiException;

    @ApiOperation(value = "", notes = "", response = Void.class, tags = {"Catalog"})
    @RequestMapping(value = "/catalogs/{name}", produces = {"application/json"}, method = RequestMethod.DELETE)
    public ResponseEntity<String> deleteCatalog(
            @ApiParam(value = "The name of the catalog to delete.", required = true) @PathVariable("name") String name) throws ApiException;

}
