/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api;

import de.ingrid.igeserver.model.InlineResponseDefault;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-08-21T10:21:42.666Z")

@Api(value = "codelist", description = "the codelist API")
@RequestMapping(path = "/api")
public interface CodelistApi {

    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "", response = Void.class),
            @ApiResponse(code = 200, message = "Unexpected error", response = InlineResponseDefault.class)
    })
    @ApiOperation(value = "", notes = "", response = Void.class, tags = {"Codelist",})

    @RequestMapping(value = "/codelist/{id}", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<String> getCodelistById(@ApiParam(value = "The ID of the codelist.", required = true) @PathVariable("id") String id);

}
