/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api

import de.ingrid.igeserver.model.HelpMessage
import io.swagger.v3.oas.annotations.Hidden
import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.Parameter
import io.swagger.v3.oas.annotations.responses.ApiResponse
import io.swagger.v3.oas.annotations.responses.ApiResponses
import io.swagger.v3.oas.annotations.tags.Tag
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod
import org.springframework.web.bind.annotation.RequestParam

@Hidden
@Tag(name = "Contexthelp", description = "the contexthelp API")
interface ContexthelpApi {
    @Operation(description = "Get the contexthelp text for a given ID.")
    @ApiResponses(value = [ApiResponse(responseCode = "200", description = "Returns the role")])
    @RequestMapping(value = ["/contexthelp"], produces = [MediaType.APPLICATION_JSON_VALUE], method = [RequestMethod.GET])
    fun getContextHelpText(
            @Parameter(description = "The unique id of the field.", required = true) @RequestParam("fieldId") id: String,
            @Parameter(description = "The active profile.", required = true) @RequestParam("profile") profile: String,
            @Parameter(description = "The current document type.", required = true) @RequestParam("docType") docType: String): ResponseEntity<HelpMessage>

    @Operation(description = "Get all fields with contexthelptexts")
    @ApiResponses(value = [ApiResponse(responseCode = "200", description = "Returns the list of field ids with contexthelptexts")])
    @RequestMapping(value = ["/contexthelpIds"], produces = [MediaType.APPLICATION_JSON_VALUE], method = [RequestMethod.GET])
    fun listContextHelpIds(
            @Parameter(description = "The active profile.", required = true) @RequestParam("profile") profile: String,
            @Parameter(description = "The current document type.", required = true) @RequestParam("docType") docType: String): ResponseEntity<List<String>>
}