/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api

import de.ingrid.igeserver.persistence.postgresql.jpa.model.ige.Group
import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.Parameter
import io.swagger.v3.oas.annotations.responses.ApiResponse
import io.swagger.v3.oas.annotations.responses.ApiResponses
import io.swagger.v3.oas.annotations.tags.Tag
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod
import java.security.Principal
import javax.validation.Valid

@Tag(name = "Groups", description = "the groups API")
interface GroupsApi {
    @Operation(description = "Creates a new group. If group with a given login already exists an error will be returned.")
    @ApiResponses(
        value = [ApiResponse(
            responseCode = "200",
            description = "Group was successfully updated"
        ), ApiResponse(
            responseCode = "400",
            description = "A group with the given login does not exist and cannot be updated"
        )]
    )
    @RequestMapping(
        value = ["/groups"],
        produces = [MediaType.APPLICATION_JSON_VALUE],
        method = [RequestMethod.POST]
    )
    fun createGroup(
        principal: Principal?,
        @Parameter(description = "Save the group into the database.", required = true) @RequestBody group: @Valid Group
    ): ResponseEntity<Void>

    @Operation(description = "Delete a group with a given ID. If group with a given id does not exists an error will be returned.")
    @ApiResponses(
        value = [ApiResponse(
            responseCode = "200",
            description = "Group was successfully deleted"
        ), ApiResponse(
            responseCode = "400",
            description = "A group with the given id does not exist and cannot be deleted"
        )]
    )
    @RequestMapping(
        value = ["/groups/{id}"],
        produces = [MediaType.APPLICATION_JSON_VALUE],
        method = [RequestMethod.DELETE]
    )
    fun deleteGroup(
        principal: Principal?,
        @Parameter(description = "The unique id of the group.", required = true) @PathVariable("id") id: Int
    ): ResponseEntity<Void>

    @Operation(description = "Get the group with the given ID.")
    @ApiResponses(value = [ApiResponse(responseCode = "200", description = "Returns the group")])
    @RequestMapping(
        value = ["/groups/{id}"],
        produces = [MediaType.APPLICATION_JSON_VALUE],
        method = [RequestMethod.GET]
    )
    fun getGroup(
        principal: Principal?,
        @Parameter(description = "The unique id of the group.", required = true) @PathVariable("id") id: Int
    ): ResponseEntity<Group>

    @Operation(description = "")
    @ApiResponses(value = [ApiResponse(responseCode = "200", description = "Returns the list of groups")])
    @RequestMapping(value = ["/groups"], produces = [MediaType.APPLICATION_JSON_VALUE], method = [RequestMethod.GET])
    fun listGroups(principal: Principal?): ResponseEntity<List<Group>>

    @Operation(description = "Updates a group. If group could not be found an error will be returned.")
    @ApiResponses(
        value = [ApiResponse(
            responseCode = "200",
            description = "Group was successfully created"
        ), ApiResponse(responseCode = "400", description = "A group already exists with the given login")]
    )
    @RequestMapping(
        value = ["/groups/{id}"],
        produces = [MediaType.APPLICATION_JSON_VALUE],
        method = [RequestMethod.PUT]
    )
    fun updateGroup(
        principal: Principal?,
        @Parameter(description = "The unique id of the group.", required = true) @PathVariable("id") id: Int,
        @Parameter(description = "Save the group into the database.", required = true) @RequestBody group: @Valid Group
    ): ResponseEntity<Group>
}
