/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api

import de.ingrid.igeserver.api.ApiException
import de.ingrid.igeserver.model.ImportAnalyzeInfo
import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.Parameter
import io.swagger.v3.oas.annotations.responses.ApiResponse
import io.swagger.v3.oas.annotations.responses.ApiResponses
import io.swagger.v3.oas.annotations.tags.Tag
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestMethod
import org.springframework.web.multipart.MultipartFile
import java.io.IOException
import javax.validation.Valid

@Tag(name = "Import", description = "the import API")
interface ImportApi {
    @Operation
    @ApiResponses(value = [ApiResponse(responseCode = "200", description = "The stored dataset, which might contain additional storage information."), ApiResponse(responseCode = "500", description = "Unexpected error")])
    @RequestMapping(value = ["/import"], produces = ["application/json"], method = [RequestMethod.POST])
    @Throws(IOException::class, ApiException::class)
    fun importDataset(@Parameter(description = "The dataset to be imported.", required = true) @RequestBody file: @Valid MultipartFile): ResponseEntity<ImportAnalyzeInfo>
}