/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api;

import de.ingrid.igeserver.model.Data4;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@Tag(name = "Import", description = "the import API")
public interface ImportApi {

    @Operation(tags = {"Import"})
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "The stored dataset, which might contain additional storage information."),
            @ApiResponse(responseCode = "500", description = "Unexpected error")})

    @RequestMapping(value = "/import", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<Void> importDataset(@Parameter(description = "The dataset to be imported.", required = true) @Valid @RequestBody Data4 data);

}
