/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api

import de.ingrid.igeserver.api.messaging.UrlReport
import de.ingrid.igeserver.model.Job
import de.ingrid.igeserver.model.JobCommand
import de.ingrid.igeserver.model.JobInfo
import io.swagger.v3.oas.annotations.Parameter
import io.swagger.v3.oas.annotations.tags.Tag
import jakarta.validation.Valid
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*
import org.springframework.web.multipart.MultipartFile
import java.security.Principal

data class UrlReplaceData(val source: UrlReport, val replaceUrl: String)

@Tag(name = "Jobs", description = "the jobs API")
interface JobsApi {

    @GetMapping(
        value = ["/jobs"],
        produces = [MediaType.APPLICATION_JSON_VALUE]
    )
    fun getJobs(
        principal: Principal
    ): ResponseEntity<Job>

    @GetMapping(
        value = ["/jobs/{id}/is-running"],
        produces = [MediaType.APPLICATION_JSON_VALUE]
    )
    fun isRunning(
        principal: Principal,
        @Parameter(description = "The ID of the job.", required = true) @PathVariable("id") id: String
    ): ResponseEntity<Boolean>

    @GetMapping(
        value = ["/jobs/{id}/info"],
        produces = [MediaType.APPLICATION_JSON_VALUE]
    )
    fun getInfo(
        principal: Principal,
        @Parameter(description = "The ID of the job.", required = true) @PathVariable("id") id: String
    ): ResponseEntity<JobInfo>

    @PostMapping(
        value = ["/jobs/url-check"],
        produces = [MediaType.APPLICATION_JSON_VALUE]
    )
    fun urlCheckTask(
        principal: Principal,
        @Parameter(description = "command for the job", required = true) @RequestParam(
            value = "command",
            required = true
        ) command: JobCommand
    ): ResponseEntity<Unit>

    @PostMapping(
        value = ["/jobs/import/analyze"],
        produces = [MediaType.APPLICATION_JSON_VALUE]
    )
    fun importAnalyzeTask(
        principal: Principal,
        @Parameter(
            description = "The dataset to be imported.",
            required = true
        ) @RequestBody file: @Valid MultipartFile,
        @Parameter(description = "command for the job", required = true) @RequestParam(
            value = "command",
            required = true
        ) command: JobCommand
    ): ResponseEntity<Unit>

    @PostMapping(
        value = ["/jobs/import"],
        produces = [MediaType.APPLICATION_JSON_VALUE]
    )
    fun importTask(
        principal: Principal,
        @Parameter(description = "command for the job", required = true) @RequestParam(
            value = "command",
            required = true
        ) command: JobCommand,
        @Parameter(required = true) @RequestBody(
            required = true
        ) options: ImportOptions
    ): ResponseEntity<Unit>

    @PostMapping(
        value = ["/jobs/url-check/replace"],
        produces = [MediaType.APPLICATION_JSON_VALUE]
    )
    fun replaceUrl(
        principal: Principal,
        @Parameter(description = "command for the job", required = true) @RequestBody(
            required = true
        ) data: UrlReplaceData
    ): ResponseEntity<Map<String, Any>>

    @PostMapping(
        value = ["/jobs/cleanup-uploads"],
        produces = [MediaType.APPLICATION_JSON_VALUE]
    )
    fun cleanupUploads(principal: Principal): ResponseEntity<Unit>

    @PostMapping(
        value = ["/jobs/remove-unreferenced-documents"],
        produces = [MediaType.APPLICATION_JSON_VALUE]
    )
    fun removeUnreferencedDocuments(principal: Principal): ResponseEntity<List<String>>

    @PostMapping(
        value = ["/jobs/update-external-coupled-resources"],
        produces = [MediaType.APPLICATION_JSON_VALUE]
    )
    fun updateExternalCoupledResources(principal: Principal): ResponseEntity<String>
}

