/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api

import de.ingrid.igeserver.services.CatalogProfile
import io.swagger.v3.oas.annotations.Hidden
import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.responses.ApiResponse
import io.swagger.v3.oas.annotations.responses.ApiResponses
import io.swagger.v3.oas.annotations.tags.Tag
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.GetMapping
import java.security.Principal

@Hidden
@Tag(name = "Profiles", description = "the profiles API")
interface ProfileApi {
    @Operation
    @GetMapping(value = ["/profiles"], produces = [MediaType.APPLICATION_JSON_VALUE])
    @ApiResponses(value = [ApiResponse(responseCode = "200", description = "")])
    fun getProfiles(principal: Principal?): ResponseEntity<List<CatalogProfile>>

//    @Operation
//    @ApiResponses(value = [ApiResponse(responseCode = "200", description = "")])
//    @RequestMapping(value = ["/profiles"], produces = [MediaType.APPLICATION_JSON_VALUE], method = [RequestMethod.POST])
//    fun uploadProfile(principal: Principal, @RequestParam("file") file: MultipartFile,
//                      redirectAttributes: RedirectAttributes): ResponseEntity<String>
}