/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import java.io.IOException;
import java.security.Principal;

@Tag(name = "Behaviours", description = "the behaviours API")
public interface ProfileApi {
    
    @Operation()
    @ApiResponses(value = { @ApiResponse(responseCode = "200", description = "") })
    @RequestMapping(value = "/profiles", produces = { "text/javascript" }, method = RequestMethod.GET)
    public ResponseEntity<String> getProfile(Principal principal) throws IOException, Exception;
    
    @Operation()
    @ApiResponses(value = { @ApiResponse(responseCode = "200", description = "") })
    @RequestMapping(value = "/profiles", produces = { "application/json" }, method = RequestMethod.POST)
    public ResponseEntity<String> uploadProfile(Principal principal, @RequestParam("file") MultipartFile file,
            RedirectAttributes redirectAttributes) throws IOException, ApiException;

}
