/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Tag(name = "RefreshToken", description = "the refreshToken API")
public interface RefreshTokenApi {

    @Operation()
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Returns a new access token to the requested client")})

    @RequestMapping(value = "/refreshToken", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<Void> refreshToken();

}
