/*
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

@Tag(name = "Upload", description = "the upload API")
public interface UploadApi {

    @RequestMapping(
            value = "/upload",
            produces = {"application/json"},
            method = RequestMethod.POST
    )
    @Operation(description = "Upload a file")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "File was successfully uploaded"),
            @ApiResponse(responseCode = "500", description = "An error occurred during upload")
    })
    ResponseEntity<Void> uploadFile(
            @Parameter(description = "The file to be uploaded", required = true) @RequestParam("file") MultipartFile file);

}
