/*
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.ingrid.igeserver.api

import de.ingrid.igeserver.model.CatalogAdmin
import de.ingrid.igeserver.model.User
import de.ingrid.igeserver.model.UserInfo
import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.Parameter
import io.swagger.v3.oas.annotations.responses.ApiResponse
import io.swagger.v3.oas.annotations.responses.ApiResponses
import io.swagger.v3.oas.annotations.tags.Tag
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.*
import java.security.Principal
import javax.validation.Valid
import javax.ws.rs.QueryParam

@Tag(name = "Users", description = "the users API")
interface UsersApi {
    @RequestMapping(
        value = ["/users"],
        produces = [MediaType.APPLICATION_JSON_VALUE],
        method = [RequestMethod.POST]
    )
    @Operation(description = "Create a new user. If the user already exists an error will be returned.")
    @ApiResponses(
        value = [ApiResponse(
            responseCode = "200",
            description = "User was successfully updated"
        ), ApiResponse(
            responseCode = "400",
            description = "A user with the given login does not exist and cannot be updated"
        )]
    )
    fun createUser(
        principal: Principal,
        @Parameter(
            description = "Save the user data into the database.",
            required = true
        ) @RequestBody user: @Valid User,
        @Parameter(description = "With this option an external user is tried to be created")
        @RequestParam(value = "newExternalUser", required = false) newExternalUser: Boolean = false
    ): ResponseEntity<Void>

    @RequestMapping(
        value = ["/users/{id}"],
        produces = [MediaType.APPLICATION_JSON_VALUE],
        method = [RequestMethod.DELETE]
    )
    @Operation(description = "The user with the given ID is deleted. If user with a given login does not exists an error will be returned.")
    @ApiResponses(
        value = [ApiResponse(
            responseCode = "200",
            description = "User was successfully deleted"
        ), ApiResponse(
            responseCode = "400",
            description = "A user with the given login does not exist and cannot be deleted"
        )]
    )
    fun deleteUser(
        principal: Principal,
        @Parameter(description = "The unique login of the user.", required = true) @PathVariable("id") userId: String
    ): ResponseEntity<Void>

    @RequestMapping(
        value = ["/users/{id}"],
        produces = [MediaType.APPLICATION_JSON_VALUE],
        method = [RequestMethod.GET]
    )
    @Operation(description = "Get the user with the given ID.")
    @ApiResponses(value = [ApiResponse(responseCode = "200", description = "Returns the user")])
    fun getUser(
        principal: Principal,
        @Parameter(description = "The unique login of the user.", required = true) @PathVariable("id") userId: String
    ): ResponseEntity<User>

    @GetMapping(
        value = ["/users/{id}/managed"],
        produces = [MediaType.APPLICATION_JSON_VALUE]
    )
    @Operation(description = "Get userIds of all users managed by the user with the given ID.")
    fun getManagedUsers(
        principal: Principal,
        @Parameter(description = "The unique id of the manager.", required = true) @PathVariable("id") userId: String
    ): ResponseEntity<List<String>>

    @RequestMapping(value = ["/users"], produces = [MediaType.APPLICATION_JSON_VALUE], method = [RequestMethod.GET])
    @Operation
    @ApiResponses(
        value = [ApiResponse(
            responseCode = "200",
            description = "Returns the list of users registered in IGE"
        )]
    )
    fun list(
        principal: Principal, @Parameter(description = "With this option an external user is tried to be created")
        @RequestParam(value = "fromUser", required = false) fromUser: String?
    ): ResponseEntity<List<User>>

    @RequestMapping(
        value = ["/users/admins"],
        produces = [MediaType.APPLICATION_JSON_VALUE],
        method = [RequestMethod.GET]
    )
    @Operation
    @ApiResponses(
        value = [ApiResponse(
            responseCode = "200",
            description = "Returns the list of users who are Catalog-Admins"
        )]
    )
    fun listCatAdmins(principal: Principal): ResponseEntity<List<User>>

    @RequestMapping(
        value = ["/users/{id}"],
        produces = [MediaType.APPLICATION_JSON_VALUE],
        method = [RequestMethod.PUT]
    )
    @Operation(description = "Updates an existing user user. If the user does not exist an error will be returned.")
    @ApiResponses(
        value = [ApiResponse(
            responseCode = "200",
            description = "User was successfully created"
        ), ApiResponse(responseCode = "400", description = "A user already exists with the given login")]
    )
    fun updateUser(
        principal: Principal,
        @Parameter(description = "The unique login of the user.", required = true) @PathVariable("id") id: String,
        @Parameter(
            description = "Save the user data into the database.",
            required = true
        ) @RequestBody user: @Valid User
    ): ResponseEntity<Void>

    @RequestMapping(
        value = ["/info/currentUser"],
        produces = [MediaType.APPLICATION_JSON_VALUE],
        method = [RequestMethod.GET]
    )
    @Operation
    @ApiResponses(
        value = [ApiResponse(responseCode = "200", description = ""), ApiResponse(
            responseCode = "400",
            description = ""
        )]
    )
    fun currentUserInfo(principal: Principal): ResponseEntity<UserInfo>

    @RequestMapping(
        value = ["/info/setCatalogAdmin"],
        produces = [MediaType.APPLICATION_JSON_VALUE],
        method = [RequestMethod.POST]
    )
    @Operation
    @ApiResponses(
        value = [ApiResponse(responseCode = "200", description = ""), ApiResponse(
            responseCode = "400",
            description = ""
        )]
    )
    fun setCatalogAdmin(
        principal: Principal,
        @Parameter(
            description = "Save the user data into the database.",
            required = true
        ) @RequestBody info: @Valid CatalogAdmin
    ): ResponseEntity<UserInfo?>

    @RequestMapping(
        value = ["/info/assignedUsers/{id}"],
        produces = [MediaType.APPLICATION_JSON_VALUE],
        method = [RequestMethod.GET]
    )
    @Operation
    @ApiResponses(value = [ApiResponse(responseCode = "200", description = "")])
    fun assignedUsers(
        principal: Principal,
        @Parameter(
            description = "The catalog id to query the assigned users from.",
            required = true
        ) @PathVariable("id") id: String
    ): ResponseEntity<List<String>>

    @RequestMapping(value = ["/user/catalog/{catalogId}"], method = [RequestMethod.POST])
    @Operation
    @ApiResponses(value = [ApiResponse(responseCode = "200", description = "")])
    fun switchCatalog(
        principal: Principal,
        @Parameter(
            description = "The id of the catalog to switch to for the current user",
            required = true
        ) @PathVariable("catalogId") catalogId: String
    ): ResponseEntity<Void>

    @RequestMapping(value = ["/info/refreshSession"], method = [RequestMethod.GET])
    @Operation
    @ApiResponses(value = [ApiResponse(responseCode = "200", description = "")])
    fun refreshSession(): ResponseEntity<Void>

    @RequestMapping(
        value = ["/externalUsers"],
        produces = [MediaType.APPLICATION_JSON_VALUE],
        method = [RequestMethod.GET]
    )
    @Operation
    @ApiResponses(
        value = [ApiResponse(
            responseCode = "200",
            description = "Returns the list of external users (keycloak)"
        )]
    )
    fun listExternal(principal: Principal): ResponseEntity<List<User>>

    @RequestMapping(
        value = ["/externalUsers/requestPasswordChange/{id}"],
        produces = [MediaType.APPLICATION_JSON_VALUE],
        method = [RequestMethod.POST]
    )
    @Operation
    @ApiResponses(
        value = [ApiResponse(
            responseCode = "200",
            description = "Sends an email to a user for changing its password"
        )]
    )
    fun requestPasswordChange(
        principal: Principal,
        @Parameter(
            description = "The user login the password change request shall be initiated.",
            required = true
        ) @PathVariable("id") id: String
    ): ResponseEntity<Void>

}
