:keycloakversion: 22.0.4-1

== Deployment

This section describes the necessary steps to deploy the IGE-NG application with all features working correctly.

The following additional components are needed:

* PostgreSQL database 13+
* Keycloak 22.0.4

optional:

* Elasticsearch 7+
* Apache/nginx
* InGrid iBus
* InGrid Codelist-Repository
* InGrid Portal

=== PostgreSQL

=== Keycloak

Keycloak is used for user management. A pre-configured docker image can be used, which already contains the realm-configuration necessary for the connection to the IGE-NG.

The docker-config should look like this:
[source, dockerfile]
====
[subs="attributes"]
  keycloak:
    image: docker-registry.wemove.com/keycloak:{keycloakversion}
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=<KEYCLOAK-ADMIN-PASSWORD>
      - KC_HTTP_RELATIVE_PATH=/keycloak
      - KC_HOSTNAME=
      - KC_HOSTNAME_URL=<URL-TO-KEYCLOAK>
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_DB=postgres
      - KC_DB_URL_HOST=db
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=<DB-PASSWORD>
      - MAIL_SMTP=mailrelay
      - MAIL_FROM=keycloak@wemove.com
      - IGE_FRONTEND_URL=http://localhost
      - IGE_SUPER_USER_LOGIN=ige
      - IGE_SUPER_USER_PASSWORD=<SUPER-ADMIN-PASSWORD>
      - IGE_SUPER_USER_FIRSTNAME=Test
      - IGE_SUPER_USER_LASTNAME=User
      - IGE_SUPER_USER_EMAIL=test.user@test.com
====

If you use your own Keycloak, then you need to do the following steps to setup the configuration with an IGE-NG installation.

==== Manual configuration

To help with the configuration of Keycloak for IGE-NG there's a config file, which contains most of the information needed to successfully support authentication for IGE-NG. When creating a new Realm, just paste the JSON-file into the given field and the realm, roles and client will be created. Then you need to do the following steps:

* create a new realm by importing this link:assets/ingrid-realm.json[JSON-file]
** update URLs in Clients -> ige-ng-frontend -> `rootUrl`, `redirectUris`, `webOrigins`
* create super-admin user "ige" (Users -> Add user)
** under "Role mapping" assign role: `ige-super-admin`
** under Credentials add a new (non-temporary) password

To configure Keycloak completely manually, the following steps are necessary:

* create a new realm "InGrid"
* create the following roles (Realm roles -> Create role)
** ige-user
*** add associated roles from "realm-management": "view-users" (Action -> Add associated roles -> Filter by clients)
** ige-user-manager
*** add associated roles from "realm-management": "manage-realm", "manage-users"
** ige-super-admin
*** add associated roles from "realm-management": "manage-realm", "manage-users"
* create super-admin user "ige" (Users -> Add user)
** under "Role mapping" assign role: `ige-super-admin`
** under Credentials add a new (non-temporary) password
* create clients (Clients -> Create client)
** ige-ng-frontend
*** client-id: "ige-ng-frontend"
*** Standard flow: "checked"
*** Direct access grants: "checked"
*** Root URL: "https://<url-to-ige-ng>"
*** Valid redirect URIs: "https://<url-to-ige-ng>/*"
*** Valid post logout redirect URIs: "+"
*** Web origins: "https://<url-to-ige-ng>"


=== Elasticsearch

=== Apache / nginx



