version: '3.1'

services:
  db:
    image: "postgres"
    restart: unless-stopped
    tmpfs:
      - /run
      - /var/cache
      - /pgdata
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080